### ISSUE TITLE
Do not try to ping gateways

### ISSUE THREAD

**Issue by Schnitzel** [lg/HowOnline#1]
First: Epic idea, usually I have an iTerm terminal open which runs a ping to 8.8.8.8

I'm using it since a couple of days, and ran into some issues, where it shows "ping gw" all the time. The issue is that some of my routers do not allow to be pinged, but pings to 8.8.8.8 work perfectly.

Maybe remove the test to ping the gateway completely? Or is there a specific idea behind?

**Comment by lg** [comment]
hm, yeah the idea is that it helps debug internet connection problems. often times it's because the gateway isn't working (wifi without a router situations). maybe there should be preferences where you can disable certain checks (like the gateway check)? or maybe try to ping 8.8.8.8 anyways?

**Comment by Schnitzel** [comment]
Good idea!
If the 8.8.8.8 ping works, do not worry about the gateway ping. If the 8.8.8.8 pink does not work, tests the gateway as well :)

/me likes non-preferences tools

**Comment by lg** [comment]
yeah i'm the same way about non-preferences tools. cool.

**Comment by lg** [comment]
fixed via https://github.com/lg/HowOnline/commit/29ecd7afcdbc611bba881d447590952e9e2c6f77. hopefully this approach will work.
