### ISSUE TITLE
Show status on click

### ISSUE THREAD

**Issue by Schnitzel** [lg/HowOnline#2]
Basically I go to the Readme of the repo to learn what the current status means, because sometimes they are not fully clear :)

what would be awesome if the current status is explained when a user clicks on the menu icon.

**Comment by lg** [comment]
probably a good idea, yes ;)

**Comment by lg** [comment]
fixed by https://github.com/lg/HowOnline/commit/1423aa105f26204be40bdc0337bdcdc8cdc8ed12
