### ISSUE TITLE
Text is unreadable on non-retina displays

### ISSUE THREAD

**Issue by wr** [lg/HowOnline#4]
![screen shot 2016-01-19 at 2 25 54 pm](https://cloud.githubusercontent.com/assets/884715/12434136/950baafa-beb9-11e5-8f25-1b76dc3c76a1.png)
![zflhit7](https://cloud.githubusercontent.com/assets/884715/12434151/a3e7056a-beb9-11e5-8e03-269a457b2e0d.gif)

**Comment by lg** [comment]
get a retina display

**Comment by wr** [comment]
worst OSS ever

**Comment by lg** [comment]
+1
