### ISSUE TITLE
Saying no IP

### ISSUE THREAD

**Issue by Mv826** [lg/HowOnline#6]
Says No IP 

I have an ip under my xfinity router 10.0.0.#

Any help?

**Comment by lg** [comment]
yeah i just experienced this too, will look into it this weekend. thanks for reporting!

**Comment by Mv826** [comment]
Thank you! I appreciate it, i tried it on a university network with the same issue as well as a hotspot

Great application though, i can use it to monitor my xfinity internet *insert rolling eye emoji here*

**Comment by lg** [comment]
fixed via https://github.com/lg/HowOnline/commit/dc0b38288dd3c867a2292b9ef62dc26b00a29e9e
